
services:
  api:
    build:
      context: .
      dockerfile: POS.Api/Dockerfile
    container_name: pos_api
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:${APP_PORT}
      - ConnectionStrings__POSConnection=${DB_CONNECTION}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pos_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"${DB_PASSWORD}\" -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
volumes:
  sql_data:
